#pragma once
#include "core.hpp"
#include "dsu.hpp"
#include "utility.hpp"
#include "modulo.hpp"
#include "number_theory.hpp"
#include "linear_algebra.hpp"
#include "combinatorics.hpp"
#include "graph_theory.hpp"
#include "persistent.hpp"
#include "time.hpp"
#include "fft.hpp"
#include "big_integer.hpp"
#include "coroutine.hpp"
#include "tree.hpp"
#include "geometry.hpp"
#include "string.hpp"
END_NS
#include "main.hpp"
BEGIN_NS
#include "segment_tree.hpp"
#include "2sat.hpp"
END_NS
#include "treap.hpp"
#include "splay_tree.hpp"
#include "queue.hpp"
