biconnected.hpp
pair<vector<char>, vector<array<ll, 2> > > biconnected(const GraphAdj &graph)
Returns articulation points and bridges of graph. graph must be connected pair of a vector with 1s for all the articulation points and a vector of bridge edges
References al, graph_theory::DFS, fo, inf, utility::min_eq, rev.
Referenced by test_biconnected.
vector<vector<vector<ll> > > ear_decomp(const GraphAdj &graph)
Returns ear decomposition of graph.
graph the graph as an adjacency list
References graph_theory::DFS, fo.
Referenced by biconnected_ear.
pair<vector<char>, vector<array<ll, 2> > > biconnected_ear(GraphAdj graph)
Finds biconnected components of graph using ear decompositions.
References graph_theory::add_edge, al, ear_decomp, fo.
Referenced by test_biconnected.