segment_tree::SegmentTree
using segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::Node = conditional_t<has_ptr, NodeExp *, ll>
using segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::Node = conditional_t<has_ptr, NodeExp *, ll>
ll segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::size_
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query.
ll segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::ceil_size
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
Node segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::root
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::~SegmentTree.
vector< NodeCore > segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::nodes
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core.
segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::SegmentTree(const ll size_arg)
segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::SegmentTree(const vector< T > &arr)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build.
auto& segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core(NodeExp *const &obj)
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
auto& segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core(const ll idx)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::nodes.
auto& segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child(NodeExp *const &obj, const ll i)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::NodeExp::child.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::destroy, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
auto segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child(const ll idx, const ll i)
void segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build(const vector< T > &arr)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::ceil_size, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::root.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::SegmentTree.
void segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build(const vector< T > &arr, const Node idx, const ll node_l, const ll node_r)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, fo, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core, linear_algebra::identity, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::mid.
void segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down([[maybe_unused]] const Node idx, const ll node_l, const ll node_r)
Push lazy updates down
References fo, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core, linear_algebra::identity.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
T segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query(const ll l, const ll r, const Node idx, const ll node_l, const ll node_r)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down, fo, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core, linear_algebra::identity, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::mid.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query.
T segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query(const ll l, const ll r, const Node custom_root)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::ceil_size, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::size_.
T segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query(const ll l, const ll r)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::root.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query.
Node segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update(const ll l, const ll r, const T val, Node idx, const ll node_l, const ll node_r)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down, fo, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core, linear_algebra::identity, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::mid.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
Node segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update(const ll l, const ll r, const T val)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::ceil_size, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::root, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
void segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::destroy(Node node)
References fo, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::~SegmentTree.
segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::~SegmentTree()
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::destroy, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::root.
segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::SegmentTree(const ll size_arg)
segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::SegmentTree(const vector< T > &arr)
auto& segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core(NodeExp *const &obj)
auto& segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_core(const ll idx)
auto& segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child(NodeExp *const &obj, const ll i)
auto segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::get_child(const ll idx, const ll i)
void segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build(const vector< T > &arr)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build.
void segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build(const vector< T > &arr, const Node idx, const ll node_l, const ll node_r)
References fo, identity.
void segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down(const Node idx, const ll node_l, const ll node_r)
Push lazy updates down
References fo, identity, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::NodeCore::qsum.
T segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query(const ll l, const ll r, const Node idx, const ll node_l, const ll node_r)
References down, fo, identity.
T segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query(const ll l, const ll r, const Node custom_root)
T segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query(const ll l, const ll r)
References segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query.
Node segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update(const ll l, const ll r, const T val, Node idx, const ll node_l, const ll node_r)
References down, fo, identity.
Node segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update(const ll l, const ll r, const T val)
void segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::destroy(Node node)
References fo.
segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::~SegmentTree()
static ll segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::mid(const ll node_l, const ll node_r, const ll i)
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
static ll segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::mid(const ll node_l, const ll node_r, const ll i)