BIT
vector<Value> BIT< Value, MonoidOp >::arr
The array storing the BIT's internal values.
Each element of this represents a range of elements.
Referenced by BIT< Value, MonoidOp >::query, BIT< Value, MonoidOp >::update.
MonoidOp BIT< Value, MonoidOp >::op
The monoid operation functor.
Referenced by BIT< Value, MonoidOp >::query, BIT< Value, MonoidOp >::update.
BIT< Value, MonoidOp >::BIT(const ll size_arg)
Construct a BIT of size size_arg.
Value BIT< Value, MonoidOp >::query(ll r) const
Returns sum of Monoid over elements in [0, r)
References BIT< Value, MonoidOp >::arr, BIT< Value, MonoidOp >::get_len, linear_algebra::identity, BIT< Value, MonoidOp >::op.
Referenced by test_bit.
void BIT< Value, MonoidOp >::update(ll idx, const Value value)
Update the value at idx by value.
Note that this does not set the value to value. idx the index of the element value the value the element will be updated by
References BIT< Value, MonoidOp >::arr, BIT< Value, MonoidOp >::get_len, BIT< Value, MonoidOp >::op.
Referenced by test_bit.
static ll BIT< Value, MonoidOp >::get_len(const ll idx)
Returns the length of the range of elements idx is responsible for.
Referenced by BIT< Value, MonoidOp >::query, BIT< Value, MonoidOp >::update.