fft.hpp
vector<com> fft(Cont v)
FFT using Cooley–Tukey FFT algorithm.
Time complexity: $ O(n log n)$
References utility::bit_ceil, fo, tau.
Referenced by conv, ifft.
vector<com> ifft(Cont v)
Returns the inverse FFT
References fft.
Referenced by conv.
auto conv(const Cont &a, const Cont &b)
Returns the convolutions of sequences a and b
References b, fft, ifft.