modulo_namespace::test
void modulo_namespace::test::test_power()
References tree::assert, modulo_namespace::modulo::modulus, modulo_namespace::power.
Referenced by test_modulo.
void modulo_namespace::test::test_md()
References tree::assert, modulo_namespace::modulo::modulus.
Referenced by test_modulo.
void modulo_namespace::test::test_modulo()
References test_md, test_power.
Referenced by test_all.