linear_algebra::test
void linear_algebra::test::test_invert_impl(const matrix< Ts... > &a)
References linear_algebra::identity, linear_algebra::invert.
Referenced by test_invert.
void linear_algebra::test::test_invert()
References b, test_invert_impl.
Referenced by test_linear_algebra.
void linear_algebra::test::test_matrix()
References b.
Referenced by test_linear_algebra.
void linear_algebra::test::test_lin_recur()
References linear_algebra::lin_recur.
Referenced by test_linear_algebra.
Polynomial<T> linear_algebra::test::lin_recur_coef(vector< T > const &c)
void linear_algebra::test::test_linear_algebra()
References test_invert, test_lin_recur, test_matrix.
Referenced by test_all.