flow::test
void flow::test::test_flow_algo(const Func &algo)
References tree::assert, flow::total_flow.
Referenced by test_flow.
matrix<ll> flow::test::random_flow()
References fo, utility::reng.
Referenced by test_compare_flow.
void flow::test::test_compare_flow(const Func1 &algo1, const Func2 &algo2, ll n_it=100)
References tree::assert, fo, random_flow, flow::total_flow.
Referenced by test_flow.
void flow::test::test_flow()
References flow::dinic, flow::edmond_karp, test_compare_flow, test_flow_algo.
Referenced by graph_theory::test::test_graph_theory.