combinatorics
T combinatorics::perm(const T a, const T b)
References utility::accumulate.
Referenced by choose, fact, permutation::identity, permute, permutation::power, string_tools::suffix_array, string_tools::test::suffix_array_naive, test_biconnected, permutation::test::test_cycles_impl, combinatorics::test::test_perm, permutation::test::test_power.
T combinatorics::fact(const T n)
References perm.
Referenced by choose, combinatorics::test::test_fact, totient.
T combinatorics::choose(const T a, const T b)
References fact, perm.
Referenced by combinatorics::test::test_choose.