permutation::test
void permutation::test::test_ops()
Referenced by test_permutation.
void permutation::test::test_cycles_impl(const Permutation &perm)
References combinatorics::perm.
Referenced by test_cycles.
void permutation::test::test_cycles()
References test_cycles_impl.
Referenced by test_permutation.
void modulo_namespace::test::test_power()
References combinatorics::perm, modulo_namespace::power, permutation::power.
Referenced by test_permutation.
void permutation::test::test_permutation()
References test_cycles, test_ops, test_power.
Referenced by main2.