string_tools
vector<ll> string_tools::prefix(string const &substring)
Returns prefix function of string s.
References fo.
Referenced by search_all.
auto string_tools::search_all(const string &text, const string &substring)
Find all substrings of text equal to substring.
Returns list of start index for each match. s must be a nonempty string
References fo, prefix.
Referenced by string_tools::test::test_search_it_one.
bool string_tools::operator==(search_it const &a, search_it const &b)
References string_tools::search_it::i.
bool string_tools::operator<(search_it const &a, search_it const &b)
References string_tools::search_it::i.
auto string_tools::search_ra(const string &text, const string &substring)
Returns a range containing all the start indices of matches of s in t.
References string_tools::search_it::ed.
Referenced by string_tools::test::search_it_all.
Permutation string_tools::suffix_array(string str)
References al, utility::counting_sort, fo, combinatorics::perm.
Referenced by string_tools::test::test_suffix_array.
vector<ll> string_tools::lcp_array(const string &str, const Permutation &suffix_arr)
References invert.
Referenced by string_tools::test::test_suffix_array.