string_tools::test
void string_tools::test::test_dict_search_impl()
References fo.
void string_tools::test::test_dict_search()
Referenced by main2.
void string_tools::test::test_hash_str()
Referenced by test_string.
void string_tools::test::test_bytehash()
References fo.
Referenced by test_string.
vector<ll> string_tools::test::brute_search_all(const string &t, const string &s)
References fo.
Referenced by test_search_it_one.
vector<ll> string_tools::test::search_it_all(const string &t, const string &s)
References cont, string_tools::search_ra.
Referenced by test_search_it_one.
void string_tools::test::test_search_it_one(const string &t, const string &s)
References brute_search_all, string_tools::search_all, search_it_all.
Referenced by test_search_it.
void string_tools::test::test_search_it()
References test_search_it_one.
Referenced by test_string.
void string_tools::test::test_string()
References test_bytehash, test_hash_str, test_search_it.
Referenced by main2.
Permutation string_tools::test::suffix_array_naive(const string &str)
References al, utility::key_compare, combinatorics::perm.
Referenced by test_suffix_array.
string string_tools::test::random_str(const ll len)
References utility::reng.
Referenced by test_suffix_array.
auto string_tools::test::lcp_array_naive(const string &str, const Permutation &suffix_arr)
References al, fo.
Referenced by test_suffix_array.
void string_tools::test::test_suffix_array()
References fo, string_tools::lcp_array, lcp_array_naive, random_str, string_tools::suffix_array, suffix_array_naive.
Referenced by main2.