graph_theory
using graph_theory::GraphAdj_Base = typedef vector<vector<ll> >
Adjacency-list representation of graph.
using graph_theory::GraphAdj = typedef vector<vector<ll> >
Adjacency-list representation of graph.
bool graph_theory::operator<(edge const &a, edge const &b)
Compare the edges by weight, with ties compared by a and b.
References graph_theory::edge::to_tuple.
bool graph_theory::operator==(edge const &a, edge const &b)
References graph_theory::edge::to_tuple.
auto & graph_theory::operator<<(Stream &os, edge const &e)
Print the edge.
References graph_theory::edge::a, graph_theory::edge::b, graph_theory::edge::weight.
auto graph_theory::shortest_dist(vector< vector< pr >> graph, ll source)
Adds edge $u \leftrightarrow v$ to graph graph.
References fo, inf.
Referenced by graph_theory::test::test_shortest_dist.
auto graph_theory::shortest_dist(matrix< ll > const &graph)
Given a 2D matrix of distances for each edge in g, returns a 2D matrix of the shortest distances.
We do not consider paths of length zero. Algorithm: Floyd-Warshall
References fo, linear_algebra::matrix< T >::is_square, linear_algebra::matrix< T >::rows_n.
auto graph_theory::mst(vector< edge > edges, const ll n)
Returns the minimum spanning forest of the set of edges es, as a set of edges
References al.
Referenced by graph_theory::test::test_mst.
vector< ll > graph_theory::get_size(const Searcher &search)
Given a searcher object, returns an array containing the size of each subtree.
References rev, tree::sz.
Referenced by centroid_decomp.
graph_theory::DFS(Graph) -> DFS< Graph >
graph_theory::BFS(Graph) -> BFS< Graph >
Referenced by tree_diameter.
auto graph_theory::trans(const GraphAdj &graph)
Returns the transpose graph of directed graph.
References fo.
Referenced by scc, graph_theory::test::test_trans.
auto graph_theory::scc(const GraphAdj &graph)
Returns the strongly connected component for each vertex of the graph g.
References trans.
Referenced by sat2::sat2, graph_theory::test::test_scc.
auto graph_theory::graph_in(GraphAdj &g, ll m)
Reads 1-indexed list of edges into graph g.
References graph_theory::GraphAdj::read.
auto graph_theory::add_edge(GraphAdj &graph, ll u, ll v)
Adds edge $u \leftrightarrow v$ to graph graph.
Referenced by biconnected_ear, test_biconnected, test_centroid_decomp, graph_draw::test::test_graph_draw, test_graph_view, test_tree_diameter.