queue_tools::test
void queue_tools::test::test_queueadaptor()
References queue_tools::QueueAdaptor< Stack >::back, queue_tools::QueueAdaptor< Stack >::empty, queue_tools::QueueAdaptor< Stack >::front, queue_tools::QueueAdaptor< Stack >::pop, queue_tools::QueueAdaptor< Stack >::push, queue_tools::QueueAdaptor< Stack >::size.
Referenced by test_queue.
void queue_tools::test::test_minstack()
References queue_tools::MinStack< T, Base >::min, queue_tools::MinStack< T, Base >::push.
Referenced by test_queue.
void queue_tools::test::test_minqueue()
References inf, queue_tools::MinQueue< T >::min, queue_tools::QueueAdaptor< MinStack< T > >::pop, queue_tools::QueueAdaptor< MinStack< T > >::push.
Referenced by test_queue.
void queue_tools::test::test_queue()
References test_minqueue, test_minstack, test_queueadaptor.
Referenced by main2.