debug_tools
constexpr auto debug_tools::light_purple_color
Referenced by main.
constexpr auto debug_tools::green_color
Referenced by main2.
constexpr auto debug_tools::red_color
Referenced by debug.
constexpr auto debug_tools::reset_color
Referenced by debug, main, main2.
ll debug_tools::depth
Referenced by debug.
auto debug_tools::type_name([[maybe_unused]] T const &v)
Referenced by simple_tp.
auto debug_tools::replace(string s, const string &a, const string &b)
Referenced by simple_tp.
auto debug_tools::simple_tp([[maybe_unused]] const T &v)
References lets, replace, type_name.
Referenced by std::operator<<, linear_algebra::operator<<.
auto debug_tools::debug(const T &x, const string &name, source_location const &loc=source_location::current())
References cerr, debug_mode, depth, fo, red_color, reset_color.