combinatorics::test
void combinatorics::test::test_perm()
References combinatorics::perm.
Referenced by test_combinatorics.
void combinatorics::test::test_fact()
References combinatorics::fact.
Referenced by test_combinatorics.
void combinatorics::test::test_choose()
References combinatorics::choose.
Referenced by test_combinatorics.
void combinatorics::test::test_combinatorics()
References test_choose, test_fact, test_perm.
Referenced by main2.