linear_algebra
auto linear_algebra::identity(const plus<>, const matrix< T > &mat)
References linear_algebra::matrix< T >::cols_n, linear_algebra::matrix< T >::rows_n.
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, sparse_table::DisjointSparseTable< T, Monoid >::DisjointSparseTable, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down, invert, utility::iterator_identity, BIT< Value, MonoidOp >::query, sparse_table::SparseTable< T, Semilattice >::query, sparse_table::DisjointSparseTable< T, Monoid >::query, hld::HLD< T, Monoid, QueryDS >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, linear_algebra::test::test_invert_impl, sparse_table::test::test_sparse_table_impl, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
auto linear_algebra::identity(const multiplies<>, const matrix< T > &mat)
References linear_algebra::matrix< T >::cols_n, fo, linear_algebra::matrix< T >::is_square, linear_algebra::matrix< T >::rows_n.
auto linear_algebra::operator+(const matrix< Ts... > &a, const matrix< Ts... > &b)
References linear_algebra::matrix< T >::cols_n, fo, linear_algebra::matrix< T >::rows_n.
auto linear_algebra::operator-(const matrix< Ts... > &a)
References linear_algebra::matrix< T >::cols_n, fo, linear_algebra::matrix< T >::rows_n.
bool linear_algebra::operator==(matrix< Ts... > const &a, matrix< Ts... > const &b)
Returns whether matrix A,B are equal.
References linear_algebra::matrix< T >::a, linear_algebra::matrix< T >::cols_n, linear_algebra::matrix< T >::rows_n.
auto linear_algebra::operator*(matrix< Ts... > const &a, matrix< Ts... > const &b)
Returns the matrix product of a and b.
References linear_algebra::matrix< T >::cols_n, fo, linear_algebra::matrix< T >::rows_n.
pair<matrix<T>, T> linear_algebra::gauss(matrix< T > b, matrix< T > a)
Returns matrix x such that $ax = b$ and the determinant of $a$ via Gaussian elimination.
References det, fo, linear_algebra::matrix< T >::is_square, linear_algebra::matrix< T >::rows_n.
Referenced by det, operator/.
matrix<Ts...> linear_algebra::invert(const matrix< Ts... > &a)
Returns inverse of the matrix.
References identity.
Referenced by linear_algebra::test::test_invert_impl.
auto linear_algebra::operator/(const matrix< Ts... > &b, const matrix< Ts... > &a)
Returns $a^{-1}b$.
References gauss.
T linear_algebra::det(const matrix< T > &a)
Returns the determinant of matrix a.
References gauss, linear_algebra::matrix< T >::rows_n.
Referenced by gauss.
auto& linear_algebra::operator<<(Stream &os, matrix< Ts... > const &m)
Print the matrix rows, line by line.
References linear_algebra::matrix< T >::cols_n, delim, fo, linear_algebra::matrix< T >::rows_n, debug_tools::simple_tp.
auto linear_algebra::lin_recur(vector< T > const &c, const ll n)
Returns nth term of linear recurrence described by c. $x(i) = x_{i-1}c_0 + x_{i-2}c_1 + \dots $ and $x(0) = 1$.
References al, fo, permutation::power.
Referenced by linear_algebra::test::test_lin_recur.