convex_hull_trick
auto convex_hull_trick::dot(point const &a, point const &b)
Referenced by graph_draw::show_dot, convex_hull_trick::test::test_cht, convex_hull_trick::test::test_dot, graph_draw::test::test_graph_draw.
auto convex_hull_trick::wedge(point const &a, point const &b)
Referenced by area, convex_hull_trick::test::test_wedge.
auto convex_hull_trick::area(const point &a, const point &b, const point &c)
References wedge.
Referenced by ccw.
bool convex_hull_trick::ccw(const point &a, const point &b, const point &c)
Returns whether moving through $a \rightarrow b \rightarrow c$ is counterclockwise.
std::invalid_argument if a, b, c are collinear and distinct. a b c bool true if counterclockwise, false otherwise.
References area.
Referenced by hull, convex_hull_trick::test::test_ccw.
auto convex_hull_trick::hull(vector< point > v, bool do_sort=true)
References al, ccw, utility::key_compare.
Referenced by convex_hull_trick::CHT::CHT, convex_hull_trick::test::test_hull.
auto convex_hull_trick::convex_min(const Range &r, const Func &f)
Returns x in Range r that minimizes the value of a convex function f(x).
References al.
Referenced by convex_hull_trick::CHT::min, convex_hull_trick::test::test_convex_min.