convex_hull_trick::test
void convex_hull_trick::test::test_less()
References tree::assert.
Referenced by test_geometry.
void convex_hull_trick::test::test_dot()
References tree::assert, convex_hull_trick::dot.
Referenced by test_geometry.
void convex_hull_trick::test::test_wedge()
References tree::assert, convex_hull_trick::wedge.
Referenced by test_geometry.
void convex_hull_trick::test::test_ccw()
References tree::assert, b, c, convex_hull_trick::ccw.
Referenced by test_geometry.
void convex_hull_trick::test::test_convex_min()
References tree::assert, convex_hull_trick::convex_min.
Referenced by test_geometry.
void convex_hull_trick::test::test_hull()
References al, tree::assert, convex_hull_trick::hull.
Referenced by test_geometry.
void convex_hull_trick::test::test_cht()
References tree::assert, convex_hull_trick::dot, fo, inf.
Referenced by test_geometry.
void convex_hull_trick::test::test_geometry()
References test_ccw, test_cht, test_convex_min, test_dot, test_hull, test_less, test_wedge.
Referenced by test_all.