utility
using utility::ar_t = typedef typename ar<T>::type
using utility::random_device = typedef random_device_patch
default_random_engine utility::reng
Referenced by test_biconnected, flow::test::random_flow, string_tools::test::random_str.
void utility::min_eq(T &x, const T &y)
Referenced by biconnected, flow::edmond_karp.
void utility::max_eq(T &x, const T &y)
Set x to the minimum of x and y.
Set x to the maximum of x and y
Referenced by centroid_decomp.
auto utility::cache(const T &f)
Set x to the minimum of x and y.
Cache calls to f using a map of type T
auto utility::uniq(Cont v, Eq const &up=Eq{}, T const &sp=T{})
Remove all duplicates element from.
v so that all elements in v are distinct and sorted
Referenced by convex_hull_trick::CHT::CHT, utility::test::test_uniq.
auto utility::key_compare(const Func &func, const Compare &compare={})
Compare using key.
func The key function compare the comparison function. A comparison functor that compares two arugments by the key.
Referenced by convex_hull_trick::CHT::CHT, convex_hull_trick::hull, std::operator<, string_tools::test::suffix_array_naive, utility::test::test_key_compare.
auto utility::prev_less(const T &v)
References fo.
ll utility::bit_ceil(ll x)
Return the smallest power of two that is at least x.
Referenced by fft, utility::test::test_bit_ceil.
ll utility::power_ceil(const ll x, const ll base)
Returns the smallest power of base that is at least x.
ll utility::log_ceil(const ll x, const ll base)
Returns the smallest exponent such that base raised to exponent is at least x.
ll utility::next_comb(ll x)
next combination of bits Formally, returns the smallest integer y > x such that popcount(y) = popcount(x).
THe desired y must exist.
Referenced by utility::test::test_next_comb.
void utility::sort2(T &a, T &b, const Func &func)
Stable sorts a and b by func.
Referenced by hld::HLD< T, Monoid, QueryDS >::func_path, dsu_ds::dsu::join.
void utility::counting_sort(Iter a, Iter b, const Proj &proj, const ll proj_size)
References al.
Referenced by string_tools::suffix_array, utility::test::test_counting_sort.
ll utility::ssize(const Cont &cont)
References cont.
Referenced by permutation::identity, bigint::operator==, bigint::BigInt::operator[], permutation::Permutation::Permutation, string_tools::Trie< start, alphabet_size >::search, sparse_table::SparseTable< T, Semilattice >::SparseTable.
bool utility::valid_idx(const vector< T > &vec, const size_t idx)
Return whether idx is a valid index for vec. Note that if idx is negative this returns false.
Referenced by utility::test::test_valid_idx.
auto utility::iterator_identity()
References linear_algebra::identity.
decltype(auto) utility::accumulate(InputIt a, InputIt b)
Referenced by combinatorics::perm, utility::test::test_accumulate, sparse_table::test::test_sparse_table_impl, flow::total_flow.
auto utility::get_partial_sum(InputIt a, InputIt b)
Referenced by utility::test::test_get_partial_sum.