tree
const ll tree::sz
Referenced by graph_theory::get_size, tm, for.
tree::b
Referenced by tm, if.
return a tree::p[0][0]
Referenced by linear_algebra::matrix< T >::matrix, permutation::invert, debug_tools::simple_tp, std::operator<<, operator+, filter, convex_hull_trick::hull, persistent::operator<<, splay_tree::SplayNode< T, has_link_cut >::rotate, tm, prime, sieve, totient, primitive_root, string_tools::prefix, string_tools::search_all.
tree::tm() struct no
References b, fo, p, rev, sz.
tree::if(da > db)
References b.
Referenced by biconnected.
tree::if(a==b)
tree::for(const auto &i :rev(ra{sz}))
References sz.
tree::assert(a->p[0]==b->p[0])
Referenced by queue_tools::QueueAdaptor< MinStack< T > >::check_invariant, divisors, dlog, splay_tree::SplayTree< T >::erase, splay_tree::SplayTree< T >::extremum, fac, linear_algebra::gauss, linear_algebra::identity, modulo_namespace::invert, splay_tree::SplayTree< T >::join, linear_algebra::matrix< T >::matrix, utility::next_comb, permutation::operator*, linear_algebra::operator*, string_tools::search_it::operator*, linear_algebra::operator+, modulo_namespace::power, prime, sparse_table::DisjointSparseTable< T, Monoid >::query, graph_theory::shortest_dist, sieve, graph_theory::test::test_add_edge, graph_theory::test::test_BFS, test_biconnected, test_bit, utility::test::test_bit_ceil, string::test::test_bytehash, convex_hull_trick::test::test_ccw, combinatorics::test::test_choose, convex_hull_trick::test::test_cht, graph_theory::bipartite::test::test_color2, flow::test::test_compare_flow, convex_hull_trick::test::test_convex_min, coroutine::test::test_coroutine, permutation::test::test_cycles_impl, test_divisors, convex_hull_trick::test::test_dot, dsu_ds::test::test_dsu, test_egcd, test_fac, combinatorics::test::test_fact, flow::test::test_flow_algo, test_graph_view, string::test::test_hash_str, hld::test::test_hld, convex_hull_trick::test::test_hull, linear_algebra::test::test_invert_impl, utility::test::test_key_compare, convex_hull_trick::test::test_less, linear_algebra::test::test_lin_recur, link_cut::test::test_link_cut_tree, linear_algebra::test::test_matrix, graph_theory::bipartite::test::test_max_match, modulo_namespace::test::test_md, queue_tools::test::test_minqueue, queue_tools::test::test_minstack, graph_theory::test::test_mst, utility::test::test_next_comb, permutation::test::test_ops, combinatorics::test::test_perm, polynomial_ns::test::test_polynomial, modulo_namespace::test::test_power, permutation::test::test_power, test_prime, test_primitive_root, queue_tools::test::test_queueadaptor, sat2::test::test_sat2, graph_theory::test::test_scc, segment_tree::test::test_segment_tree_impl, graph_theory::test::test_shortest_dist, test_sieve, sparse_table::test::test_sparse_table_impl, splay_tree::test::test_splay_tree, test_totient, graph_theory::test::test_trans, test_tree_diameter, utility::test::test_uniq, convex_hull_trick::test::test_wedge, utility::test::test_with, totient, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.