graph_theory::bipartite
auto graph_theory::bipartite::color2(const vector< vl > &graph)
Returns a bipartite coloring if possible
References b, fo.
Referenced by max_match, graph_theory::bipartite::test::test_color2.
auto graph_theory::bipartite::max_match(const vector< vl > &graph)
Returns a maximum matching of bipartite graph using the Hopcroft-Karp algorithm.
References b, color2, fo, inf.
Referenced by graph_theory::bipartite::test::test_max_match.
ll graph_theory::bipartite::matching_size(const vl &matching)
Returns the size of the matching.
matching must be a a vector where idx is matched with matching[idx], or not matched if matching[idx] = -1
References al.
Referenced by graph_theory::bipartite::test::test_max_match.