permutation
Permutation permutation::identity(multiplies<>, const Permutation &perm)
References combinatorics::perm, utility::ssize.
Permutation permutation::operator*(const Permutation &a, const Permutation &b)
Returns the composition of permutations a and b, so that ret[i] = a[b[i]].
$a\cdot b$
References fo.
Permutation permutation::invert(multiplies<>, const Permutation &p)
Inverts a permutation.
p Permutation. Inverse of the permutation.
References fo.
Permutation permutation::power(const Permutation &perm, ll n)
Returns in linear-time, perm^n using cycle-decomposition.
perm A permutation. n The exponent. If negative, returns the power of the inverse permutation. $\left(perm\right)^n$
References combinatorics::perm.
Referenced by dlog, linear_algebra::lin_recur, prime, primitive_root, test_dlog, permutation::test::test_power.