modulo_namespace
using modulo_namespace::invert_t = typedef decltype(invert(std::declval<Args>()...))
T modulo_namespace::power(T a, ll b)
Returns $a^b$.
a the base b the exponent Time complexity: $O(\log_2 |b|)$ multiplications
References tree::assert, b, identity, invert, ret.
Referenced by invert, modulo_namespace::test::test_power, permutation::test::test_power.
ll modulo_namespace::mod(ll a, const ll b)
Returns the remainder of a divided by b as a nonnegative integer in [0, b).
References b.
Referenced by dlog, egcd, mod_eq.
ll modulo_namespace::mod_eq(ll &a, const ll b)
Set a to the remainder when divided by b.
References b, mod.
modulo modulo_namespace::operator""_M(const unsigned long long x)
modulo modulo_namespace::identity(plus<>, modulo)
Referenced by power.
modulo modulo_namespace::identity(multiplies<>, modulo)
modulo modulo_namespace::operator+(modulo const &a, modulo const &b)
References b, modulo_namespace::modulo::modulus, modulo_namespace::modulo::x.
modulo modulo_namespace::operator++(modulo &a)
modulo modulo_namespace::operator-(modulo const &a)
References modulo_namespace::modulo::modulus, modulo_namespace::modulo::x.
modulo_namespace::bin(==, modulo)
modulo modulo_namespace::operator*(modulo const &a, modulo const &b)
References b, modulo_namespace::modulo::modulus, modulo_namespace::modulo::x.
modulo modulo_namespace::invert(multiplies<>, modulo const &b)
References tree::assert, b, modulo_namespace::modulo::modulus, power.
Referenced by power.
auto& modulo_namespace::operator<<(Stream &os, modulo const &m)
References modulo_namespace::modulo::x.