link_cut
typedef SplayNode< ll, true > link_cut::Node
Node * link_cut::make_tree()
Referenced by link_cut::test::test_link_cut_tree.
void link_cut::detach_child(Node *node)
References splay_tree::SplayNode< T, has_link_cut >::child.
Referenced by access.
Node * link_cut::access(Node *node)
References splay_tree::SplayNode< T, has_link_cut >::attach, splay_tree::SplayNode< T, has_link_cut >::child, detach_child, splay_tree::SplayNode< T, has_link_cut >::splay.
Referenced by cut, find_root, lca, link.
Node * link_cut::find_root(Node *node)
References access, splay_tree::SplayNode< T, has_link_cut >::child.
Referenced by lca, link_cut::test::test_link_cut_tree.
void link_cut::cut(Node *node)
References access, splay_tree::SplayNode< T, has_link_cut >::child.
Referenced by link_cut::test::test_link_cut_tree.
void link_cut::link(Node *par, Node *child)
References access, splay_tree::SplayNode< T, has_link_cut >::attach.
Referenced by string_tools::Trie< start, alphabet_size >::exit_link, string_tools::Trie< start, alphabet_size >::go, link_cut::test::test_link_cut_tree.
Node * link_cut::lca(Node *u, Node *v)
References access, find_root.
Referenced by link_cut::test::test_link_cut_tree.