flow
matrix<ll> flow::edmond_karp(const matrix< ll > &capacity)
References graph_theory::BFS, fo, inf, utility::min_eq, linear_algebra::matrix< T >::rows_n.
Referenced by flow::test::test_flow.
matrix<ll> flow::dinic(const matrix< ll > &capacity)
References graph_theory::BFS, fo, inf, linear_algebra::matrix< T >::rows_n.
Referenced by flow::test::test_flow.
ll flow::total_flow(const matrix< ll > &flow)
Referenced by flow::test::test_compare_flow, flow::test::test_flow_algo.