number_theory.hpp
vector<ll> divs
Referenced by prime, fac.
auto prime(ll n)
Return whether integer n >= 2 is prime.
References al, divs, fo, permutation::power.
Referenced by fac, test_prime.
vector<ll> divisors(ll x)
Return all divisors of x in sorted order.
References al, fo.
Referenced by test_divisors.
vector<ll> sieve(ll n)
Linear time prime sieve.
n Sieve numbers in [0,n) a vector where ret[idx] is the smallest prime divisor of idx
References fo.
Referenced by test_sieve.
unordered_map<ll, ll> fac(ll n)
Returns the factorization of n.
a map from the prime to the exponent
References divs, prime.
Referenced by primitive_root, test_fac, totient.
void egcd(const ll a, const ll b, ll &x, ll &y)
Sets x and y so that $x\cdot a + y\cdot b = \gcd(a,b)$.
References modulo_namespace::mod.
Referenced by test_egcd.
ll totient(ll n)
Returns the totient of the integer n.
n >= 1
References fac, combinatorics::fact.
Referenced by dlog, primitive_root, test_totient.
ll dlog(const modulo a, const modulo b)
Finds x such that a^x = b (mod M) using baby-step giant-step algorithm.
a and M must be coprime.
References fo, modulo_namespace::mod, permutation::power, totient.
Referenced by test_dlog.
modulo primitive_root()
Returns a primitive root modulo M.
References fac, fo, permutation::power, totient.
Referenced by test_primitive_root.