operations.hpp
aug
ret
const range< T > & b
Referenced by conv, linear_algebra::operator+, polynomial_ns::operator+, polynomial_ns::operator*, polynomial_ns::operator%, polynomial_ns::operator==, linear_algebra::test::test_invert, linear_algebra::test::test_matrix, combinatorics::perm, combinatorics::choose, permutation::operator*, lets_add::lets_add, graph_theory::operator<, graph_theory::operator==, graph_theory::shortest_dist, debug_tools::replace, operator/, operator-, operator!=, operator<=, operator>=, operator>, operator+, operator|, operator&, fo, Max::operator(), Min::operator(), utility::swap2, std::operator<, convex_hull_trick::dot, convex_hull_trick::wedge, convex_hull_trick::area, convex_hull_trick::ccw, persistent::first_cmp::operator(), queue_tools::QueueAdaptor< MinStack< T > >::pop, splay_tree::SplayTree< T >::join, convex_hull_trick::test::test_ccw, graph_theory::bipartite::color2, graph_theory::bipartite::max_match, graph_theory::test::test_BFS, graph_disunion, tree_diameter, modulo_namespace::power, modulo_namespace::mod, modulo_namespace::mod_eq, modulo_namespace::operator+, modulo_namespace::operator*, modulo_namespace::invert, prime, fac, egcd, dlog, test_egcd, test_dlog, ll::operator+=, operator<, operator==, operator%, std::operator+, string_tools::operator==, string_tools::operator<.
return ret
Referenced by graph_theory::mst, int_it< T >::operator--, int_it< T >::operator++, utility::next_comb, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, join, graph_theory::test::test_mst, graph_disunion, hld::HLD< T, Monoid, QueryDS >::query, test_tree_diameter, modulo_namespace::power.
return c
Referenced by linear_algebra::operator+, linear_algebra::operator-, permutation::operator*, graph_theory::scc, fo, convex_hull_trick::area, convex_hull_trick::ccw, convex_hull_trick::test::test_ccw, tree_diameter, fac.
auto operator+=(T1 &a, const T2 &b)
auto operator-=(T1 &a, const T2 &b)
auto operator*=(T1 &a, const T2 &b)
auto operator/=(T1 &a, const T2 &b)
enable_if_t<is_floating_point_v<T>, T> invert(multiplies<>, const T &x)
Referenced by operator/, linear_algebra::test::test_invert_impl.
Group operator/(Group const &a, Group const &b)
References b, invert.
constexpr auto operator-(const T1 &a, const T2 &b)
References b.
constexpr auto operator!=(const T1 &a, const T2 &b)
References b.
auto operator<=(const T1 &a, const T2 &b)
References b.
auto operator>=(const T1 &a, const T2 &b)
References b.
auto operator>(const T1 &a, const T2 &b)
References b.
tm() using uset
Range class. This represents a begin and end iterator pair. A for-range loop can iterate over a range object.
um operator+(um a, um const &b)
References b, tree::p.
auto operator|(unordered_set< T > const &a, unordered_set< T > const &b)
Returns union of sets a and b.
a p_a:... b p_b:... the union of sets a and b
References al, b, ret.
auto operator&(unordered_set< T > const &a, unordered_set< T > const &b)
References b, ret.
tm() auto sub_set(unordered_set< T > const &a
return sub_set(a, b, ret)
sub_set(b, a, ret)
vector<T> c(a.size())
fo(i, a.size())
References b, c.
Referenced by biconnected, biconnected_ear, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, graph_theory::bipartite::color2, debug_tools::debug, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::destroy, sparse_table::DisjointSparseTable< T, Monoid >::DisjointSparseTable, divisors, dlog, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down, ear_decomp, flow::edmond_karp, fft, graph_disunion, graph_theory::graph_in, graph_draw::graph_to_dot, string_tools::hash_str::hash_str, linear_algebra::identity, permutation::invert, main, linear_algebra::matrix< T >::matrix, graph_theory::bipartite::max_match, polynomial_ns::operator%, graph_theory::GeneralSearch< DFS >::operator(), polynomial_ns::operator*, permutation::operator*, polynomial_ns::operator+, linear_algebra::operator+, linear_algebra::operator-, dsu_ds::operator<<, permutation::Permutation::Permutation, permute, string_tools::prefix, utility::prev_less, prime, primitive_root, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, sat2::sat2, string_tools::search_all, graph_theory::shortest_dist, sieve, sparse_table::SparseTable< T, Semilattice >::SparseTable, test_biconnected, graph_theory::bipartite::test::test_bipartite, string::test::test_bytehash, convex_hull_trick::test::test_cht, test_dlog, dsu_ds::test::test_dsu, graph_theory::bipartite::test::test_max_match, segment_tree::test::test_segment_tree_impl, graph_theory::test::test_shortest_dist, sparse_table::test::test_sparse_table_impl, tree::tm, permutation::Permutation::to_cycles, graph_theory::trans, tree_diameter, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
auto operator+(Iterator it, enable_if_t<!is_same< typename iterator_traits< decltype(it)>::iterator_category, random_access_iterator_tag >::value, ll > n)
constexpr ll identity(bin_op< ll const & > const &f)
References inf, ret.
constexpr ll identity(bin_op< ll > const &f)
References ret.
ll identity(plus<>, ll)
ll identity(multiplies<>, ll)
ll identity(Max, ll)
References inf.
ll identity(Min, ll)
References inf.