range.hpp
bin
isect
using ra = range<int_it<ll> >
auto operator==(int_it< T > const &a, int_it< T > const &b)
auto operator<(int_it< T > const &a, int_it< T > const &b)
Referenced by std::operator<.
auto operator<(range< T > const &a, range< T > const &b)
References b, range< T >::bg, range< T >::ed.
auto operator&(range< T > const &a, range< T > const &b)
References b, range< T >::bg, range< T >::ed.
auto rev(const Range &r)
Referenced by biconnected, centroid_decomp, tree::no< T >::dp, graph_theory::get_size, tree::lca.
int_it<T> operator+(int_it< T > const &a, int_it< T > const &b)
References b, int_it< T >::x.
int_it<T> operator-(int_it< T > const &a)
References int_it< T >::x.
auto intersect(const T1 &a, const T2 &b)
References b, cont, dis, eq, null, over.
Referenced by operator^.
auto operator^(range< T > const &a, range< T > const &b)
References b, intersect.
auto filter(vector< ra > &v)
References al.