string_tools::Trie
bool string_tools::Trie< start, alphabet_size >::leaf
Whether this node is a leaf node
Referenced by string_tools::Trie< start, alphabet_size >::exit_link.
string string_tools::Trie< start, alphabet_size >::str
The string for this leaf node
Referenced by string_tools::Trie< start, alphabet_size >::insert, string_tools::Trie< start, alphabet_size >::find_leaf, string_tools::Trie< start, alphabet_size >::find_node.
Trie* string_tools::Trie< start, alphabet_size >::parent
Parent of this node
Referenced by string_tools::Trie< start, alphabet_size >::next_default, string_tools::Trie< start, alphabet_size >::link, string_tools::Trie< start, alphabet_size >::go, string_tools::Trie< start, alphabet_size >::exit_link.
char string_tools::Trie< start, alphabet_size >::edge_char
Character for the edge to the parent
Referenced by string_tools::Trie< start, alphabet_size >::next_default, string_tools::Trie< start, alphabet_size >::link.
array<Trie *, alphabet_size> string_tools::Trie< start, alphabet_size >::next_storage
Referenced by string_tools::Trie< start, alphabet_size >::next.
array<Trie *, alphabet_size> string_tools::Trie< start, alphabet_size >::go_cache
Referenced by string_tools::Trie< start, alphabet_size >::go.
Trie* string_tools::Trie< start, alphabet_size >::suffix_link_cache
Referenced by string_tools::Trie< start, alphabet_size >::link.
Trie* string_tools::Trie< start, alphabet_size >::exit_link_cache
Referenced by string_tools::Trie< start, alphabet_size >::exit_link.
Trie*& string_tools::Trie< start, alphabet_size >::next(const char c)
Returns the child corresponding to the character c.
References string_tools::Trie< start, alphabet_size >::next_storage.
Referenced by string_tools::Trie< start, alphabet_size >::find_node, string_tools::Trie< start, alphabet_size >::go, string_tools::Trie< start, alphabet_size >::next, string_tools::Trie< start, alphabet_size >::next_default.
auto& string_tools::Trie< start, alphabet_size >::next(const char c) const
References string_tools::Trie< start, alphabet_size >::next.
Trie* string_tools::Trie< start, alphabet_size >::next_default(const char c)
Returns the child corresponding to the character c. A new child is created if no such child exists.
References string_tools::Trie< start, alphabet_size >::edge_char, string_tools::Trie< start, alphabet_size >::next, string_tools::Trie< start, alphabet_size >::parent.
void string_tools::Trie< start, alphabet_size >::insert(const string &str)
inserts str into the trie
References string_tools::Trie< start, alphabet_size >::str.
Trie* string_tools::Trie< start, alphabet_size >::find_leaf(const string &str)
Return the leaf node for str, or nullptr if none exists.
References string_tools::Trie< start, alphabet_size >::find_node, string_tools::Trie< start, alphabet_size >::str.
Trie* string_tools::Trie< start, alphabet_size >::find_node(const string &str)
Returns node corresponding to str (including non-leaf nodes), otherwise nullptr.
References string_tools::Trie< start, alphabet_size >::next, string_tools::Trie< start, alphabet_size >::str.
Referenced by string_tools::Trie< start, alphabet_size >::find_leaf.
Trie* string_tools::Trie< start, alphabet_size >::link()
returns the suffix link
References string_tools::Trie< start, alphabet_size >::edge_char, string_tools::Trie< start, alphabet_size >::go, string_tools::Trie< start, alphabet_size >::link, string_tools::Trie< start, alphabet_size >::parent, string_tools::Trie< start, alphabet_size >::suffix_link_cache.
Referenced by string_tools::Trie< start, alphabet_size >::exit_link, string_tools::Trie< start, alphabet_size >::go, string_tools::Trie< start, alphabet_size >::link.
Trie* string_tools::Trie< start, alphabet_size >::go(const char c)
Goes to the node for the largest suffix of the current string plus c.
References string_tools::Trie< start, alphabet_size >::go, string_tools::Trie< start, alphabet_size >::go_cache, string_tools::Trie< start, alphabet_size >::link, string_tools::Trie< start, alphabet_size >::next, string_tools::Trie< start, alphabet_size >::parent.
Referenced by string_tools::Trie< start, alphabet_size >::go, string_tools::Trie< start, alphabet_size >::link.
Trie* string_tools::Trie< start, alphabet_size >::exit_link()
Returns the exit link, the next leaf suffix.
References string_tools::Trie< start, alphabet_size >::exit_link_cache, string_tools::Trie< start, alphabet_size >::leaf, string_tools::Trie< start, alphabet_size >::link, string_tools::Trie< start, alphabet_size >::parent.
auto string_tools::Trie< start, alphabet_size >::search(const string &text)
Searches for the patterns in text.
a vector of ((left, right), node) pairs for each match where [left, right) is the range of the match, and node is the node corresponding to the match. character of the match
References fo, utility::ssize.