graph_theory::GraphAdj
void graph_theory::GraphAdj::add_edge(const ll u, const ll v)
Referenced by biconnected_ear, read, graph_theory::test::test_add_edge, graph_theory::test::test_BFS, test_centroid_decomp, graph_theory::bipartite::test::test_color2, graph_draw::test::test_graph_draw, test_graph_view, graph_theory::bipartite::test::test_max_match.
void graph_theory::GraphAdj::read(const ll num_edges)
References add_edge, cin, fo, LAMBDA.
Referenced by graph_theory::graph_in.