dsu_ds::dsu
vector< ll > dsu_ds::dsu::parent
The parent of each element.
Referenced by dsu, find, join, dsu_ds::operator<<, biconnected, ear_decomp, hld::HLD< T, Monoid, QueryDS >::func_path.
vector< ll > dsu_ds::dsu::size_
Size of set of representative element idx
Referenced by join.
dsu_ds::dsu::dsu(const ll n)
Construct a dsu with n elements.
Initially each element is in its own set.
References al, parent.
ll dsu_ds::dsu::find(ll x) const
Returns the representative element of x.
References find, parent.
Referenced by find, join, dsu_ds::operator<<.
bool dsu_ds::dsu::join(ll x, ll y)
Joins the set containing x with the set containing y.
true if the set containing x is different from the set containing y. Returns false otherwise, since nothing is done.
References find, parent, size_, utility::swap2.
dsu_ds::dsu::dsu(const ll n)
Construct a dsu with n elements.
Initially each element is in its own set.
References al.
ll dsu_ds::dsu::find(ll x) const
Returns the representative element of x.
References find.
Referenced by find.
bool dsu_ds::dsu::join(ll x, ll y)
Joins the set containing x with the set containing y.
true if the set containing x is different from the set containing y. Returns false otherwise, since nothing is done.
References utility::swap2.