linear_algebra::matrix
ll linear_algebra::matrix< T >::rows_n
Referenced by linear_algebra::matrix< T >::matrix, linear_algebra::matrix< T >::is_square, linear_algebra::identity, linear_algebra::operator+, linear_algebra::operator-, linear_algebra::operator==, linear_algebra::operator*, linear_algebra::gauss, linear_algebra::det, linear_algebra::operator<<, graph_theory::shortest_dist, flow::edmond_karp, flow::dinic.
ll linear_algebra::matrix< T >::cols_n
Row, column.
Referenced by linear_algebra::matrix< T >::matrix, linear_algebra::matrix< T >::operator[], linear_algebra::matrix< T >::is_square, linear_algebra::identity, linear_algebra::operator+, linear_algebra::operator-, linear_algebra::operator==, linear_algebra::operator*, linear_algebra::operator<<.
vector<T> linear_algebra::matrix< T >::a
Referenced by linear_algebra::matrix< T >::operator[], linear_algebra::operator==.
linear_algebra::matrix< T >::matrix(ll r_, ll c_, T v={})
Array storing the data, in row-major order.
linear_algebra::matrix< T >::matrix(T d)
linear_algebra::matrix< T >::matrix(vector< vector< pr >> const &g)
References fo, linear_algebra::matrix< T >::rows_n.
linear_algebra::matrix< T >::matrix(const initializer_list< initializer_list< ll >> &vals)
References linear_algebra::matrix< T >::cols_n, fo, linear_algebra::matrix< T >::rows_n.
auto linear_algebra::matrix< T >::operator[](const ll i)
auto linear_algebra::matrix< T >::operator[](const ll i) const
References linear_algebra::matrix< T >::a, linear_algebra::matrix< T >::cols_n.
bool linear_algebra::matrix< T >::is_square() const
Returns true if matrix is a square matrix.
References linear_algebra::matrix< T >::cols_n, linear_algebra::matrix< T >::rows_n.
Referenced by linear_algebra::gauss, linear_algebra::identity, graph_theory::shortest_dist.