test_number_theory.hpp
void test_prime()
References prime.
Referenced by test_number_theory.
void test_divisors()
References divisors.
Referenced by test_number_theory.
void test_sieve()
References sieve.
Referenced by test_number_theory.
void test_fac()
References fac.
Referenced by test_number_theory.
void test_egcd(ll a, ll b)
References egcd.
Referenced by test_egcd, test_number_theory.
void test_egcd()
References test_egcd.
void test_totient()
References totient.
Referenced by test_number_theory.
void test_dlog()
References dlog, fo, permutation::power.
Referenced by test_number_theory.
void test_primitive_root()
References primitive_root.
Referenced by test_number_theory.
void test_number_theory()
References test_divisors, test_dlog, test_egcd, test_fac, test_prime, test_primitive_root, test_sieve, test_totient.
Referenced by test_all.