test_compiled.cpp
PRE
Contains core files for the template
fo
Contains core files for the template
fr
al
rel_assert
WARN
TODO
paste2
paste
lets_count
let
import
bin
aug
FUNCTOR
Expands to a functor type that calls func.
NDEBUG
dbg
lambda
DEFINE_FUNC_EQ
USE_RANDOM_DEVICE_PATCH
CO_SWITCH
cobegin
coend
coreturn
isect
using ull = unsigned long long
using ll = long long
using ld = long double
using pr = pair<ll, ll>
using com = complex<double>
using point = complex<ll>
using prio_queue_t = std::priority_queue<T, vector<T>, Comp>
using clock_ = high_resolution_clock
using ra = range<int_it<ll> >
using Max = struct { template <typename... Ts> decltype(auto) operator()(Ts &&... args) const { return ( max )(forward<decltype(args)>(args)...)
using Min = struct { template <typename... Ts> decltype(auto) operator()(Ts &&... args) const { return ( min )(forward<decltype(args)>(args)...)
bool debug_mode
Referenced by main.
vector<pair<string, string> > lets
Referenced by lets_add::lets_add.
lets_add _l__COUNTER__
constexpr auto inf
Infinity
Referenced by identity, polynomial_ns::Polynomial< T >::degree, queue_tools::MinStack< T >::min, biconnected, centroid_decomp.
auto const delim
Delimiter for debug output
Referenced by operator<<.
constexpr auto tau
Pi
bool multitest
Referenced by main.
auto& in
Referenced by rin::operator<<, main.
vector<ll> divs
Referenced by prime, fac.
auto operator==(int_it< T > const &a, int_it< T > const &b)
auto operator<(int_it< T > const &a, int_it< T > const &b)
auto operator<(range< T > const &a, range< T > const &b)
References range< T >::bg, range< T >::ed.
auto operator&(range< T > const &a, range< T > const &b)
References range< T >::bg, range< T >::ed.
auto rev(const Range &r)
Referenced by biconnected, centroid_decomp.
int_it<T> operator+(int_it< T > const &a, int_it< T > const &b)
References int_it< T >::x.
int_it<T> operator-(int_it< T > const &a)
References int_it< T >::x.
auto intersect(const T1 &a, const T2 &b)
References cont, dis, eq, null, over.
Referenced by operator^.
auto operator^(range< T > const &a, range< T > const &b)
References intersect.
auto filter(vector< ra > &v)
References al.
auto operator+=(T1 &a, const T2 &b)
auto operator-=(T1 &a, const T2 &b)
auto operator*=(T1 &a, const T2 &b)
auto operator/=(T1 &a, const T2 &b)
enable_if_t<is_floating_point_v<T>, T> invert(multiplies<>, const T &x)
Referenced by operator/.
Group operator/(Group const &a, Group const &b)
References invert.
constexpr auto operator-(const T1 &a, const T2 &b)
constexpr auto operator!=(const T1 &a, const T2 &b)
auto operator<=(const T1 &a, const T2 &b)
auto operator>=(const T1 &a, const T2 &b)
auto operator>(const T1 &a, const T2 &b)
unordered_map<ll, ll> operator+(unordered_map< ll, ll > a, unordered_map< ll, ll > const &b)
auto operator|(unordered_set< T > const &a, unordered_set< T > const &b)
Returns union of sets a and b.
a p_a:... b p_b:... the union of sets a and b
References al.
auto operator&(unordered_set< T > const &a, unordered_set< T > const &b)
auto sub_set(unordered_set< T > const &a, unordered_set< T > const &b, unordered_set< T > &ret)
Referenced by operator-, operator^.
auto operator-(unordered_set< T > const &a, unordered_set< T > const &b)
References sub_set.
auto operator^(unordered_set< T > const &a, unordered_set< T > const &b)
References sub_set.
auto operator*(vector< T > a, vector< T > b)
References fo.
auto operator+(Iterator it, enable_if_t<!is_same< typename iterator_traits< decltype(it)>::iterator_category, random_access_iterator_tag >::value, ll > n)
ll identity(plus<>, ll)
Referenced by segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::build, sparse_table::DisjointSparseTable< T, Monoid >::DisjointSparseTable, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::down, BIT< Value, MonoidOp >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, sparse_table::SparseTable< T, Semilattice >::query, sparse_table::DisjointSparseTable< T, Monoid >::query, hld::HLD< T, Monoid, QueryDS >::query, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
ll identity(multiplies<>, ll)
ll identity(Max, ll)
References inf.
ll identity(Min, ll)
References inf.
auto operator<<(R &r, const T &x) -> decltype(r.in >> const_cast< T & >(x), declval< enable_if_t< is_same< R, rin >::value, rin & >>())
enable_if_t<is_same<T, istream>::value, rin> operator>>(Stream &is, T &x)
auto& operator<<(Stream &os, tuple< T... > t)
References delim.
auto print(const T1 &arg1, const Ts &... args)
void main2()
References test_bit, combinatorics::test::test_combinatorics, coroutine::test::test_coroutine, utility::test::test_counting_sort, string_tools::test::test_dict_search, dsu_ds::test::test_dsu, convex_hull_trick::test::test_geometry, graph_draw::test::test_graph_draw, graph_theory::test::test_graph_theory, hld::test::test_hld, linear_algebra::test::test_linear_algebra, link_cut::test::test_link_cut_tree, modulo_namespace::test::test_modulo, test_number_theory, permutation::test::test_permutation, polynomial_ns::test::test_polynomial, queue_tools::test::test_queue, sat2::test::test_sat2, segment_tree::test::test_segment_tree, sparse_table::test::test_sparse_table, splay_tree::test::test_splay_tree, string_tools::test::test_string, string_tools::test::test_suffix_array, utility::test::test_utility.
Referenced by main.
int main(int argc, char *argv[])
References cerr, debug_mode, fo, in, main2, multitest.
void test_bit()
References BIT< Value, MonoidOp >::query, BIT< Value, MonoidOp >::update.
Referenced by main2.
pair<vector<char>, vector<array<ll, 2> > > biconnected(const GraphAdj &graph)
Returns articulation points and bridges of graph. pair of a vector with 1s for all the articulation points and a vector of bridge edges
References al, fo, inf, utility::min_eq, dsu_ds::dsu::parent, rev.
Referenced by test_biconnected.
vector<vector<vector<ll> > > ear_decomp(const GraphAdj &graph)
Returns ear decomposition of graph.
graph the graph as an adjacency list
References fo, dsu_ds::dsu::parent.
Referenced by biconnected_ear.
pair<vector<char>, vector<array<ll, 2> > > biconnected_ear(GraphAdj graph)
Finds biconnected components of graph using ear decompositions.
References graph_theory::add_edge, ear_decomp, fo.
Referenced by test_biconnected.
GraphAdj permute(const vector< ll > &perm, const GraphAdj &graph)
References fo, combinatorics::perm.
Referenced by test_biconnected.
GraphAdj graph_disunion(const GraphAdj &a, const GraphAdj &b)
References fo.
Referenced by test_biconnected.
void test_biconnected()
References graph_theory::add_edge, al, biconnected, biconnected_ear, fo, graph_disunion, combinatorics::perm, permute, utility::reng.
void test_graph_view()
References graph_theory::add_edge, fo.
pair<array<ll, 2>, ll> tree_diameter(const GraphAdj &g)
Find tree diameter.
Returns diameter and center of a tree :param: g
References fo.
Referenced by test_tree_diameter.
void test_tree_diameter()
References graph_theory::add_edge, al, tree_diameter.
vector<vector<ll> > centroid_decomp(const Graph &tree)
Centroid decomposition of a tree.
cent_lvl where cent_lvl[i][j] is the jth centroid on the path from the root to i
References al, graph_theory::get_size, inf, utility::max_eq, rev, tree::sz.
Referenced by test_centroid_decomp.
void test_centroid_decomp()
References graph_theory::add_edge, centroid_decomp, fo.
auto prime(ll n)
Return whether integer n >= 2 is prime.
References al, divs, fo, permutation::power.
Referenced by fac, test_prime.
vector<ll> divisors(ll x)
Return all divisors of x in sorted order.
References al, fo.
Referenced by test_divisors.
vector<ll> sieve(ll n)
Linear time prime sieve.
n Sieve numbers in [0,n) a vector where ret[idx] is the smallest prime divisor of idx
References fo.
Referenced by test_sieve.
unordered_map<ll, ll> fac(ll n)
Returns the factorization of n.
a map from the prime to the exponent
References divs, prime.
Referenced by primitive_root, test_fac, totient.
void egcd(const ll a, const ll b, ll &x, ll &y)
Sets x and y so that $x\cdot a + y\cdot b = \gcd(a,b)$.
References modulo_namespace::mod.
Referenced by test_egcd.
ll totient(ll n)
Returns the totient of the integer n.
n >= 1
References fac, combinatorics::fact.
Referenced by dlog, primitive_root, test_totient.
ll dlog(const modulo a, const modulo b)
Finds x such that a^x = b (mod M) using baby-step giant-step algorithm.
a and M must be coprime.
References fo, modulo_namespace::mod, permutation::power, totient.
Referenced by test_dlog.
modulo primitive_root()
Returns a primitive root modulo M.
References fac, fo, permutation::power, totient.
Referenced by test_primitive_root.
void test_prime()
References prime.
Referenced by test_number_theory.
void test_divisors()
References divisors.
Referenced by test_number_theory.
void test_sieve()
References sieve.
Referenced by test_number_theory.
void test_fac()
References fac.
Referenced by test_number_theory.
void test_egcd(ll a, ll b)
References egcd.
Referenced by test_egcd, test_number_theory.
void test_egcd()
References test_egcd.
void test_totient()
References totient.
Referenced by test_number_theory.
void test_dlog()
References dlog, fo, permutation::power.
Referenced by test_number_theory.
void test_primitive_root()
References primitive_root.
Referenced by test_number_theory.
void test_number_theory()
References test_divisors, test_dlog, test_egcd, test_fac, test_prime, test_primitive_root, test_sieve, test_totient.
Referenced by main2.