treap.hpp
flip
using treap_t = treap<Key, Data_Temp<Key> >
size_data<Key> operator+(size_data< Key > const &l, size_data< Key > const &r)
Returns the data for a node given the data for the children.
References size_data< Key >::size.
ostream& operator<<(Stream &os, size_data< Key > const &data)
Print size data
References size_data< Key >::size.
Data get_data(treap< Key, Data > *trp)
Get data associated with the treap node
References treap< Key, Data >::data.
Referenced by split_imp, update_data.
void update_data(Trp *trp)
References get_data.
Referenced by erase, insert, join, split, split_imp.
void split(treap< Key, Data > *trp, const Key &key, Trp *&l, Trp *&r)
Splits the treap by key
References treap< Key, Data >::l, treap< Key, Data >::r, update_data.
Referenced by insert.
Trp* join(Trp *l, Trp *r)
Joins treap l and treap r.
All the keys in l must be less than the keys in r. Trp A treap type. l The left half r The right half Trp*: The union of l and r.
References down, update_data.
Referenced by erase, splay_tree::SplayTree< T >::erase, erase_imp, get_imp, insert_imp.
void insert(Trp *&trp, Trp *x)
inserts Node x into treap
x the new node to be inserted trp the treap the node is inserted into
References split, update_data.
Referenced by insert, splay_tree::SplayTree< T >::insert.
auto insert(treap< Key, Data > *&trp, const Key &key)
insert a node with key
key into trp
References insert.
void erase(treap< Key, Data > *&trp, const Key &key)
erase the node with key
key from the treap trp
References join, treap< Key, Data >::key, treap< Key, Data >::l, treap< Key, Data >::r, update_data.
void down(Trp *trp)
References flip.
Referenced by join, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::query, split_imp, segment_tree::SegmentTree< T, Query, Update, has_lazy, has_ptr, has_pers, base >::update.
void split_imp(Trp *trp, ll pos, Trp *&l, Trp *&r, ll sum=0)
References down, get_data, update_data.
Referenced by erase_imp, get_imp, insert_imp.
void insert_imp(Trp *&trp, Trp *x, ll pos)
Insert a node x at position pos
References join, split_imp.
Referenced by insert_imp.
void erase_imp(Trp *&trp, ll pos)
Erase the node at position pos
References join, split_imp.
auto get_imp(Trp *&trp, ll pos)
Get the node at positions pos
References join, split_imp.
auto insert_imp(treap< Key, Data > *&trp, Key const &key, ll pos)
Insert the node with key at position pos into trp
References insert_imp.
auto& operator<<(Stream &os, treap< Ts... > *trp)
Debug print the treap
References treap< Key, Data >::data, treap< Key, Data >::key, treap< Key, Data >::l, treap< Key, Data >::pri, treap< Key, Data >::r.
void to_array(treap< Key, Data > *trp, vector< Key > &out)
Insert the elements of trp in-order into out
References treap< Key, Data >::key, treap< Key, Data >::l, treap< Key, Data >::r.
Referenced by to_array.
vector<Key> to_array(treap< Key, Data > *trp)
References to_array.