#pragma once
/** @brief Abbreviations for various types. Useful for competitive programming. */
#define I(x)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
	ll x;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
	cin >> x;
#define pb push_back
#define vc vector
let(vl, vector<ll>);
using bt = bitset<numeric_limits<ll>::digits>;
let(um, unordered_map<ll, ll>);
